"""ShopAssist database connectivity, schema provisioning, and catalog validation module."""

from shopassist.db.connection import (
    check_connection,
    get_async_database_url,
    get_async_engine,
)
from shopassist.db.indexing import (
    audit_indexes,
    benchmark_query_plans,
    execute_index_migration,
    export_index_report,
    EXPECTED_INDEXES,
    IndexAuditItem,
    IndexAuditResult,
    IndexDefinition,
    IndexState,
    run_phase5_7_pipeline,
    validate_all_indexes,
    validate_database_integrity_post_indexing,
)
from shopassist.db.ingestion import (
    audit_database_state,
    BatchIngestionMetrics,
    DatabaseAuditResult,
    DatabaseState,
    export_ingestion_report,
    format_product_record,
    format_vector_literal,
    ingest_products,
    PostIngestionValidationMetrics,
    run_phase5_6_pipeline,
    validate_post_ingestion,
    validate_source_parquet,
)
from shopassist.db.search_validation import (
    CANONICAL_PARQUET_PATH,
    DEFAULT_REPORT_PATH,
    EXPECTED_CATALOG_SIZE,
    EXPECTED_CATEGORY_COUNT,
    EXPECTED_EMBEDDING_DIM,
    ValidationTestResult,
    export_validation_report,
    run_phase5_8_full_validation,
    validate_group_a_integrity,
    validate_group_b_filtering,
    validate_group_c_vector_search,
    validate_group_d_filtered_semantic,
    validate_group_e_index_performance,
)
from shopassist.db.validation import (
    enable_pgvector,
    provision_base_schema,
    run_transactional_smoke_test,
    validate_constraints,
    validate_deferred_indexes,
    validate_products_table_schema,
    validate_updated_at_trigger,
    validate_vector_dimension,
)

__all__ = [
    "get_async_database_url",
    "get_async_engine",
    "check_connection",
    "enable_pgvector",
    "provision_base_schema",
    "validate_products_table_schema",
    "validate_vector_dimension",
    "validate_constraints",
    "validate_updated_at_trigger",
    "validate_deferred_indexes",
    "run_transactional_smoke_test",
    "audit_database_state",
    "DatabaseAuditResult",
    "DatabaseState",
    "BatchIngestionMetrics",
    "PostIngestionValidationMetrics",
    "format_product_record",
    "format_vector_literal",
    "ingest_products",
    "validate_post_ingestion",
    "validate_source_parquet",
    "run_phase5_6_pipeline",
    "export_ingestion_report",
    "audit_indexes",
    "benchmark_query_plans",
    "execute_index_migration",
    "export_index_report",
    "EXPECTED_INDEXES",
    "IndexAuditItem",
    "IndexAuditResult",
    "IndexDefinition",
    "IndexState",
    "run_phase5_7_pipeline",
    "validate_all_indexes",
    "validate_database_integrity_post_indexing",
    "CANONICAL_PARQUET_PATH",
    "DEFAULT_REPORT_PATH",
    "EXPECTED_CATALOG_SIZE",
    "EXPECTED_CATEGORY_COUNT",
    "EXPECTED_EMBEDDING_DIM",
    "ValidationTestResult",
    "export_validation_report",
    "run_phase5_8_full_validation",
    "validate_group_a_integrity",
    "validate_group_b_filtering",
    "validate_group_c_vector_search",
    "validate_group_d_filtered_semantic",
    "validate_group_e_index_performance",
]


